require_relative 'android/apk'
require_relative 'android/manifest'
require_relative 'android/axml_parser'
require_relative 'android/dex'
require_relative 'android/resource'
require_relative 'android/utils'
require_relative 'android/layout'
